language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install -r test-requirements.txt
    - python setup.py develop
script: make test
notifications:
    slack: metwork-framework:dAfaodV8XzpmqIcje2zE3jcn
